name: Deploy and Dockerize React App v1

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest-large
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build React App and Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Image to Docker Hub
      run: |
        docker push mjhos/portfolio

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEBSERVER_HOST }}
        username: ${{ secrets.WEBSERVER_USERNAME }}
        password: ${{ secrets.WEBSERVER_PASS }}
        port: ${{ secrets.WEBSERVER_PORT }}
        script: |
          docker pull mjhos/portfolio
          docker stop portfolio-container || true
          docker run -d --name portfolio-container -p 8001:80 mjhos/portfolio
