name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_REPO }}:latest --push . 
        docker tag ${{ secrets.DOCKERHUB_REPO }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
        docker push ${{ secrets.DOCKERHUB_REPO }}:latest

    - name: List Docker Images
      run: docker images
      

  deploy:
    runs-on: ubuntu-latest

    needs: docker

    steps:
    - name: SSH into web server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEBSERVER_HOST }}
        username: ${{ secrets.WEBSERVER_USERNAME }}
        key: ${{ secrets.WEBSERVER_SSH_KEY }}
        port: ${{ secrets.WEBSERVER_PORT }}

    - name: Pull and run Docker image
      run: |
        docker pull ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
        docker stop portfolio || true
        docker rm portfolio || true
        docker run -d --name portfolio -p 8001:80 ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}
