name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build React App and Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Image to Docker Hub
      run: |
        docker push mjhos/portfolio

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WEBSERVER_HOST}}
        username: ${{ secrets.WEBSERVER_USERNAME }}
        key: ${{ secrets.WEBSERVER_SSH_KEY }}
        script: |
          docker pull mjhos/portfolio
          docker stop web-container || true
          docker run -d --name portfolio -p 8001:80 mjhos/portfolio
